### ISSUE TITLE
Windows installation issue

### ISSUE THREAD

**Issue by theRedCount** [Peco602/rusthunter#2]
although I have run powershell as administrator I have the problem reported in screenshot

![immagine](https://user-images.githubusercontent.com/14308209/168988036-ffb1e004-bc9b-429a-ae38-8e4aebeffbfb.png)

**Comment by theRedCount** [comment]
I solved as follow:
1) Run powershell as Administrator
2) Typing: powershell -ep bypass
3) run installer: .\rusthunter.ps1 install

**Comment by Peco602** [comment]
To run a Powershell script you first need to change the execution policy:

```ps1
powershell -ep bypass
```
