### ISSUE TITLE
Snapshot doesn't work/start  ->  The tool has not been installed yet

### ISSUE THREAD

**Issue by theRedCount** [Peco602/rusthunter#3]
I have just installed the tool as reported in official documentation.
but when i try to execute a snapshot with the follow command:
`.\rusthunter.ps1 global -HostsFile .\hosts -ConfigFile .\config`

I obtain this:
![immagine](https://user-images.githubusercontent.com/14308209/169020841-133df96c-823d-4d71-83e4-3dc7971a7275.png)

And if I try to reinstall it:
![immagine](https://user-images.githubusercontent.com/14308209/169021572-6cbe82d3-6de8-4127-882f-9c050564a257.png)

**Comment by Peco602** [comment]
There is an error in the rusthunter.ps1 installation function. 

I will analyse and fix it as soon as possible.

**Comment by Peco602** [comment]
Please checkout the dev branch and test it again.
